### ISSUE TITLE
Startup Crash with Archers (RPG Series) & REI

### ISSUE THREAD

**Issue by SlayDigger** [Sinytra/ConnectorExtras#17]
### Describe the bug

Archers (RPG Series) Seems to crash with REI (Forge) installed.

### Steps to reproduce

1. Install Archers RPG Series, REI Forge, Connector, Connector Extras, and all of their dependencies (Azurelib Armour (Forge), Spell Engine, Spell Power Attributes, Trinkets, Architectury Api (Forge), Projectile Damage Attribute, & Player Animator
2. Launch the game

### Logs

https://pastebin.com/uLCSqj8g

**Comment by Su5eD** [comment]
You are missing required dependencies. See lines 154 - 164 in the log.

**Comment by SlayDigger** [comment]
I could of sworn that I checked to see if the problem persisted after... Woopsy daisy : (
