### ISSUE TITLE
InvalidMixinException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by Madis0** [Sinytra/ConnectorExtras#18]
### Describe the bug

My mod won't run due to a mixin error but I don't understand why. Works on equivalent Fabric for MC 1.20.1.

### Steps to reproduce

1. Install [OneBar 4.0.0](https://modrinth.com/mod/onebar/version/4.0.0), the Forge version of Cloth Config, Sinytra Connector, Forgified Fabric API, Connector Extras for Forge 47.2.0 on Minecraft 1.20.1
2. Try to run
3. Get a crash
...

### Logs

https://github.com/Madis0/OneBar/issues/72

### Additional context

My mod only depends on Fabric API and Cloth Config and uses some mixins
Source: https://github.com/Madis0/OneBar/tree/1.20.1

**Comment by Su5eD** [comment]
Is this caused by Connector Extras or Connector itself?

**Comment by Madis0** [comment]
Good point, I think I misunderstood ConnectorExtras as I get a similar crash without it (and I probably don't need it either).
