### ISSUE TITLE
crash with absolute ultracraft

### ISSUE THREAD

**Issue by frangnosquest** [Sinytra/ConnectorExtras#21]
### Describe the bug

game crashes on mod loading if both mods are installed, seems like an issue with mixins

### Steps to reproduce

1. install connector extras along with sinytra connector and forgified fabric api
2. install absolute ultracraft along with azurelib
3. launch the game

### Logs

https://pastebin.com/UUK6gyk3

### Additional context

Link to the mod in question: https://www.curseforge.com/minecraft/mc-mods/absolute-ultracraft

**Comment by Su5eD** [comment]
Does this also occur without Connector Extras installed?

**Comment by frangnosquest** [comment]
it occurs only if connector extras is installed

**Comment by Su5eD** [comment]
Fixed in 5b22b019f3027067e8f0771ba7f7cf542b659296
