### ISSUE TITLE
Connector extras fail processing when uploading as server files

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/ConnectorExtras#24]
![image](https://github.com/Sinytra/ConnectorExtras/assets/13007677/134561c6-5fc2-4862-afe4-1f80c59bc3a1)

Am unsure why but it makes uploading go under manual review and take longer.
Only applies to server files

**Comment by Su5eD** [comment]
Unfortunately, this is outside my control. I don't know how CurseForge comes to the conclusion Connector Extras may be "obfuscated" or "contain corrupt files". The review system and malware scanner are not public, therefore it's hard to tell what's really going on. Therefore, my best recommendation is to contact CurseForge support and ask them about it.

**Comment by AzureDoom** [comment]
The easy fix is don't include the mods/.connector folder in your exports or server packs. That will cause this everytime and there is no reason to ship the .connector folder as it always simply just generate on the first run anyway.

**Comment by Xplodin** [comment]
I don't include the .connector folder. I make sure to delete it if I test the server files. 
 
  On Fri, Jan 5, 2024 at 8:08 PM, ***@***.***> wrote:   


The easy fix is don't include the mods/.connector folder in your exports or server packs. That will cause this everytime and there is no reason to ship the .connector folder as it always simply just generate on the first run anyway.
