### ISSUE TITLE
VS2 +Eureka incompatible with connector extras

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/ConnectorExtras#25]
### Describe the bug

mixin conflict with reach entity attributes

### Steps to reproduce

1.add the mods required to boot vs2, eureka, connector + extras
2. throw in create big cannons just to be safe
3. crash
...

### Logs

https://gist.github.com/Xplodin/40305731d05955764ce79db7768ad308

### Additional context

I believe both mods have a conflict with reach entity attributes
Looked at both mod's code

**Comment by Xplodin** [comment]
Actually this is VS2 and Eureka with connector.
Mod could just be broken rn. not connector or extras fault here

**Comment by Xplodin** [comment]
seems to be embeddium I believe

**Comment by CherrieTheShifter** [comment]
is this fixed

https://github.com/Sinytra/ConnectorExtras/issues/76

**Comment by Xplodin** [comment]
something likely changed between vs2 update and connector
