### ISSUE TITLE
incorrectly showing clickable "Config" button for Dynamic Surroundings

### ISSUE THREAD

**Issue by EnderHane** [Sinytra/ConnectorExtras#36]
### Describe the bug

"Config" button for Dynamic Surroundings is clickable in Mods menu, which is different in native Fabric or even when replacing ConnectorExtras with ModMenu.

### Steps to reproduce

1. 
  - install Connector Extras and all its dependencies.
  - install Dynamic Surroundings

and go to Dynamic Surroundings in mod list

2. 
  - remove Connector Extras 
  - install Mod Menu

and go to Dynamic Surroundings in mod list

### Logs

with Catalogue (crash): 
https://pastebin.com/raw/pSdE2TN5

without Catalogue (not crash):
https://pastebin.com/raw/ACv8YL6Y

### Additional context

Both in NeoForge primitive Mods menu (i.e. without Catalogue installed) and in Catalogue menu the button is clickable. However, clicking it crashs the game in Catalogue, while nothing happens (except for a similar NullPointerException stacktrace) in the primitive menu.

**Comment by Su5eD** [comment]
> nothing happens (except for a similar NullPointerException stacktrace) in the primitive menu.

I cannot reproduce this. I've installed Connector Extras and Connector beta 42 with dynamic surroundings and the Forge mod menu works fine. Try using Forge 47.1.3
