### ISSUE TITLE
latest continiuty incompat with connector extra

### ISSUE THREAD

**Issue by liangmoe** [Sinytra/ConnectorExtras#38]
### Describe the bug

Try the latest continiuty with connector extra but failed

### Steps to reproduce

1. install sinytra, connector extra and continiuty
2. launch the game
3. crash on startup
...

### Logs

https://mclo.gs/1ZSNB8g

### Additional context

latest continiuty: https://modrinth.com/mod/continuity/version/3.0.0-beta.5+1.20.1

**Comment by Aulberon** [comment]
The problem continues to this day
