### ISSUE TITLE
Crash with REI Plugin Compatibilities

### ISSUE THREAD

**Issue by onecvly** [Sinytra/ConnectorExtras#4]
### Describe the bug

Unable to launch the game

### Steps to reproduce

Load REI, REI Plugin Compatibilities and this mod together

### Logs

https://gist.github.com/onecvly/112339ddd2ad7809d8446c3468d69286

### Additional context

REI Plugin Compatibilities：This is an external REI module to workaround issues brought forward by mods accessing JEI apis, by remapping those usages back to their REI equivalent code.

**Comment by Su5eD** [comment]
Unfortunately, there don't seem to be any errors in the logs. Can you upload a crash report?
