### ISSUE TITLE
Missing:org/sinytra/connector/loader/ConnectorEarlyLoader

### ISSUE THREAD

**Issue by krzj** [Sinytra/ConnectorExtras#44]
### Describe the bug

Missing:org/sinytra/connector/loader/ConnectorEarlyLoader

### Steps to reproduce

1.
2.
3.
...

**Comment by krzj** [comment]
1.11.1

**Comment by Su5eD** [comment]
Update Connector to beta 44 or downgrade Connector Extras to 1.10.x. Connector Extras 1.11.x is meant to be used with Connector beta 44 and later.
