### ISSUE TITLE
[feature] defile from doctor4t

### ISSUE THREAD

**Issue by electikos** [Sinytra/ConnectorExtras#54]
the problem is this mixin: defile.mixins.json:client.inkling.adapter_generated_ForgeGui

It need to access the ratatouille mod to get this mixin.

**Comment by Tkcool1** [comment]
> the problem is this mixin: defile.mixins.json:client.inkling.adapter_generated_ForgeGui
> 
> It need to access the ratatouille mod to get this mixin.

You can get Defile working fairly easily by removing InklingLivingEntitiyMixin and InklingDisableHungerBarInGameHudMixin from both Defile.json and from the mixin folder in the Defile.jar and it'll load fine (only things these two mixins affect is the humger bar not being removed while submerged in ink and the bar when you charge the jump being missing)

If you having trouble getting it to work, go to the Sinytra discord and go to the support channel to find the Defile post where I posted a working modlist for Defile.

**Comment by electikos** [comment]
thank you
