### ISSUE TITLE
Crash with Pehkui 3.7.8

### ISSUE THREAD

**Issue by Gremter** [Sinytra/ConnectorExtras#7]
### Describe the bug

Pehkui crashes with Connector Extras 1.4.1. Works fine with only Sinytra Connector beta.19 and Forgified Fabric API 0.90.0 1.9.25

### Steps to reproduce

1. Install Sinytra Connector beta.19, Forgified Fabric API 0.90.0 1.9.25 and Connector Extras 1.4.1
2. Add Pehkui
3. Crash at launch

### Logs

https://pastebin.com/5DMfsW6K

### Additional context

Tested with only Pehkui 3.7.8 forge, fabric seems to not be working too

**Comment by Su5eD** [comment]
It appears both Pehkui and REA attempt to modify the same constant number in order to increase the available reach distance for accessing containers. Unfortunately, mixin doesn't allow chaining this kind of injection, so the best solution here is to make the mixins optional.
