### ISSUE TITLE
Incompatibility with JEI and TechReborn

### ISSUE THREAD

**Issue by litjohn50** [Sinytra/ConnectorExtras#9]
### Describe the bug

Recipes for inside the machines are missing for techreborn

### Steps to reproduce

1. Install mods
2. Place down a tech reborn grinder
3. Place a diamond inside watch it grind to diamond dust
4.  View JEI Recipes for Diamond Dust 
5. Notice recipe using the grinder is missing only the crafting one
...

### Logs

N/A

### Additional context

Connector-1.0.0-beta.19+1.20.1-full.jar
ConnectorExtras-1.4.1+1.20.1.jar
fabric-api-0.90.0+1.9.27+1.20.1.jar
TechReborn-5.8.7.jar
jei-1.20.1-forge-15.2.0.27.jar

Inside the machine
![image](https://github.com/Sinytra/ConnectorExtras/assets/28884916/c9aee220-7596-4d6c-90fa-d02932fa2cc8)

What JEI tell you
![image](https://github.com/Sinytra/ConnectorExtras/assets/28884916/329432aa-d733-42ca-9d27-e5f1a89ee2f9)

You can see recipes for crafting machines, but can't see recipes for crafting inside machines. Some reason only REI allows you too.

**Comment by Su5eD** [comment]
That is correct, Tech Reborn contains no JEI plugin and only integrates with REI. If you wish to look up TR recipes, you'll need to use REI.

**Comment by litjohn50** [comment]
Oof no way to bridge to JEI? REI is having many issues on its own that I had to deal with.

**Comment by Su5eD** [comment]
Unfortunately I'm not aware of any REI->JEI bridges. Both EMI and REI can run JEI plugins, but it doesn't work the other way around.
